# Site settings
title: Bitknowledge
email: bitknowledge0@gmail.com
url: https://bitknowledge.github.io
description: "Wellcome to thr biggest BANGLADESHI tutorial based blog"
skills: "you can join with us by sending an email"
meta_author: Jobayer Ahmed Mickey

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Bitknowlwdge
  social: web.facebook.com/bitknowledge0

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: gmail
    url: bitknowledge0@gmail.com
  - title: facebook
    url: web.facebook.com/bitknowledge0
  - title: github
    url: http://github.com/Bitknowledge


# Credits content


# Build settings
markdown: kramdown
permalink: pretty
